"""fix: user_project team_project

Revision ID: 4713da31db85
Revises: 72c462637f26
Create Date: 2024-06-01 13:42:28.893881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4713da31db85'
down_revision: Union[str, None] = '72c462637f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teamproject_user_project_id_key', 'teamproject', type_='unique')
    op.drop_constraint('teamproject_user_project_id_fkey', 'teamproject', type_='foreignkey')
    op.drop_column('teamproject', 'user_project_id')
    op.drop_constraint('userproject_team_project_id_key', 'userproject', type_='unique')
    op.drop_constraint('userproject_team_project_id_fkey', 'userproject', type_='foreignkey')
    op.drop_column('userproject', 'team_project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userproject', sa.Column('team_project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('userproject_team_project_id_fkey', 'userproject', 'teamproject', ['team_project_id'], ['id'])
    op.create_unique_constraint('userproject_team_project_id_key', 'userproject', ['team_project_id'])
    op.add_column('teamproject', sa.Column('user_project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('teamproject_user_project_id_fkey', 'teamproject', 'userproject', ['user_project_id'], ['id'])
    op.create_unique_constraint('teamproject_user_project_id_key', 'teamproject', ['user_project_id'])
    # ### end Alembic commands ###
