"""foreign keys fixes

Revision ID: 72c462637f26
Revises: cf516e96fa15
Create Date: 2024-06-01 13:39:19.249783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '72c462637f26'
down_revision: Union[str, None] = 'cf516e96fa15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userproject', sa.Column('team_project_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'userproject', ['team_project_id'])
    op.create_foreign_key(None, 'userproject', 'teamproject', ['team_project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userproject', type_='foreignkey')
    op.drop_constraint(None, 'userproject', type_='unique')
    op.drop_column('userproject', 'team_project_id')
    # ### end Alembic commands ###
